version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: radar_rent_db
    environment:
      POSTGRES_USER: radar_user
      POSTGRES_PASSWORD: radar_password
      POSTGRES_DB: radar_rent
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 